from typing import List, Dict
from groq import Groq

from backend import config

_client = None

GROQ_MODEL = "llama-3.1-8b-instant"  # fast + free-tier friendly on Groq

SYSTEM_PROMPT = (
    "You are a helpful assistant that answers questions using ONLY the provided "
    "context chunks. If the context doesn't contain enough information to answer "
    "the question, say so clearly instead of guessing. Keep answers concise and "
    "cite which source(s) you used by filename."
)


def _get_client() -> Groq:
    global _client
    if _client is None:
        if not config.GROQ_API_KEY:
            raise ValueError(
                "GROQ_API_KEY is not set. Add it to your .env file or environment variables."
            )
        _client = Groq(api_key=config.GROQ_API_KEY)
    return _client


def _build_context(chunks: List[Dict]) -> str:
    blocks = []
    for i, chunk in enumerate(chunks, start=1):
        filename = chunk.get("filename", "unknown")
        blocks.append(f"[Source {i}: {filename}]\n{chunk['text']}")
    return "\n\n".join(blocks)


def generate_answer_stream(query: str, chunks: List[Dict]):
    """
    Same as generate_answer, but yields tokens as they're generated by Groq.
    Yields plain text chunks (strings). Caller is responsible for SSE framing.
    """
    if not chunks:
        yield "I couldn't find any relevant information in the document corpus to answer this question."
        return

    client = _get_client()
    context = _build_context(chunks)

    user_prompt = (
        f"Context:\n{context}\n\n"
        f"Question: {query}\n\n"
        f"Answer the question using only the context above."
    )

    stream = client.chat.completions.create(
        model=GROQ_MODEL,
        messages=[
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": user_prompt},
        ],
        temperature=0.2,
        max_tokens=500,
        stream=True,
    )

    for chunk in stream:
        delta = chunk.choices[0].delta.content
        if delta:
            yield delta


def generate_answer(query: str, chunks: List[Dict]) -> Dict:
    """
    Generate a grounded answer from retrieved chunks using Groq.
    Returns: { "answer": str, "model": str, "sources_used": [filenames] }
    """
    if not chunks:
        return {
            "answer": "I couldn't find any relevant information in the document corpus to answer this question.",
            "model": GROQ_MODEL,
            "sources_used": [],
        }

    client = _get_client()
    context = _build_context(chunks)

    user_prompt = (
        f"Context:\n{context}\n\n"
        f"Question: {query}\n\n"
        f"Answer the question using only the context above."
    )

    response = client.chat.completions.create(
        model=GROQ_MODEL,
        messages=[
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": user_prompt},
        ],
        temperature=0.2,
        max_tokens=500,
    )

    answer = response.choices[0].message.content
    sources_used = list({c.get("filename") for c in chunks if c.get("filename")})

    return {
        "answer": answer,
        "model": GROQ_MODEL,
        "sources_used": sources_used,
    }